scr_collision_init();
grav = 0.5;
depth = -4;
grounded = false;
scr_sound(sfx_breakdance);
audio_falloff_set_model(audio_falloff_linear_distance);
audio_listener_orientation(0, 0, 1, 0, -1, 0);
c_emit = audio_emitter_create();
c_snd = audio_play_sound_on(c_emit, sfx_boombox, 1, 10);
audio_emitter_falloff(c_emit, 300, 1000, 1);
audio_sound_gain(c_snd, 0, 0);
